const PERMISSIONS = {
  CONTRIBUTOR: [
    'CREATE_SUBMISSION',
    'VIEW_OWN_SUBMISSIONS',
    'RESUBMIT_SUBMISSION'
  ],
  REVIEWER: [
    'VIEW_ALL_SUBMISSIONS',
    'REVIEW_SUBMISSION'
  ],
  ADMIN: [
    'VIEW_ALL_SUBMISSIONS',
    'REVIEW_SUBMISSION',
    'MANAGE_USERS',
    'VIEW_ANALYTICS',
    'DELETE_USER'
  ]
};

module.exports = PERMISSIONS;